### PR TITLE
fix(naming): rename OVH to OVHcloud

### PR DESCRIPTION
**Pull request by jpatovh**
Since OVH name moved to OVHcloud, please change it ASAP.

Thx

### CODE REVIEW

**Review by lizardK — APPROVED** [review]

**Comment by cbourgois** [comment]
⚠️ BREAKING CHANGES

**Review by antleblanc — CHANGES_REQUESTED** [review]
@blaryjp Thanks for your contribution.

I don't know if you have pay attention to your change but it seems to be a :boom: breaking change.

IMO it's a bit too earlier to start these kind of changes.

In fact it also implies to rename the repository.

What I propose you is to create a `next` branch that will contains your patch.

Do you agree?

**Review by Jisay — APPROVED** [review]

**Comment by antleblanc** [comment]
@blaryjp FYI I have created a new branch `next`. Your pull request now target this new branch.

**Comment by antleblanc** [comment]
@blaryjp Travis checks has been fixed in both `master` and `next` branch. Could you please rebase your branch on `next` branch?

Thank you!

**Comment by jpatovh** [comment]
> @blaryjp Travis checks has been fixed in both `master` and `next` branch. Could you please rebase your branch on `next` branch?
> 
> Thank you!

Done. Thank you for your awesome work.

**Pull request merged**
